# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end',
        ),
    ]
